 
package Telas;
 
import java.awt.Color;

public class TelaPedidos extends javax.swing.JInternalFrame {
 
    TelaClientes cli;
    TelaVendas venda;
    TelaVendasAbertas vendasAbertas;
    
    public TelaPedidos() {
        initComponents();
        this.getContentPane().setBackground(Color.gray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_produtos1 = new javax.swing.JButton();
        Btn_relatorios = new javax.swing.JButton();

        setClosable(true);
        setTitle("Tela pedidos");

        Btn_produtos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/carrinhowa.png"))); // NOI18N
        Btn_produtos1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        Btn_produtos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_produtos1ActionPerformed(evt);
            }
        });

        Btn_relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lupa.png"))); // NOI18N
        Btn_relatorios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controle de vendas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        Btn_relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_relatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(Btn_produtos1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(Btn_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_produtos1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(321, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_produtos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_produtos1ActionPerformed
        venda = new TelaVendas();
        TelaPrincipal.DesktopP.add(venda);
        venda.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_produtos1ActionPerformed

    private void Btn_relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_relatoriosActionPerformed
        vendasAbertas = new TelaVendasAbertas();
        TelaPrincipal.DesktopP.add(vendasAbertas);
        vendasAbertas.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_relatoriosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_produtos1;
    private javax.swing.JButton Btn_relatorios;
    // End of variables declaration//GEN-END:variables
}
